# Hand-maintained app cask for the DevDeck menu-bar app (DevDeck.app).
#
# Unlike Casks/devdeck-server.rb (the CLI), this cask is NOT generated by
# GoReleaser: the .app ships inside the signed/notarized DMG, which GoReleaser
# attaches to the release via `release.extra_files` rather than building as an
# archive — so it cannot template the DMG url/sha256 or emit an app cask for it.
# Bump `version` and `sha256` at release time (see the devdeck-release skill).
#
# The DMG is universal (single artifact for Intel + Apple Silicon), so there is
# no on_intel/on_arm split. The .app bundles the server, frontmost, and menuctl
# binaries in Contents/Resources, so no postflight helper-copy is required.
cask "devdeck" do
  version "0.5.1"
  sha256 "13ad89f59d2be3cfb723fddad80ae57f7287c14bce3bde3c8255fbfe4c6a5ea6"

  url "https://github.com/devdeck-app/devdeck-releases/releases/download/v#{version}/DevDeck-#{version}.dmg"
  name "DevDeck"
  desc "Menu-bar app that turns your phone into a developer macro pad"
  homepage "https://github.com/devdeck-app/devdeck-releases"

  # Versions are hand-bumped at release time; the app self-updates via Sparkle.
  livecheck do
    skip "Updated on release; macapp auto-updates via Sparkle."
  end

  # The app self-updates via Sparkle (SUFeedURL https://devdeck.app/appcast.xml),
  # so Homebrew defers version checks to Sparkle.
  auto_updates true
  depends_on macos: :sonoma

  app "DevDeck.app"

  uninstall quit: "com.devdeck.MacApp"

  zap trash: [
    "~/Library/Caches/com.devdeck.MacApp",
    "~/Library/HTTPStorages/com.devdeck.MacApp",
    "~/Library/Preferences/com.devdeck.MacApp.plist",
  ]
end
