# This file was generated by GoReleaser. DO NOT EDIT.
cask "devdeck-server" do
  version "0.5.6"

  on_macos do
    on_arm do
      sha256 "11ee5d4f3b3830a57b234b4df7f96553d9b6a49b2e0f8509df04d23478c42177"
      url "https://github.com/devdeck-app/devdeck-releases/releases/download/v#{version}/devdeck-server_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6be64199532eb438bdf177e6f94882fcbb6565cdca4aa102906e0c7903a75795"
      url "https://github.com/devdeck-app/devdeck-releases/releases/download/v#{version}/devdeck-server_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "devdeck-server"
  desc "DevDeck server for the DevDeck mobile app"
  homepage "https://github.com/devdeck-app/devdeck-server"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devdeck-server"

  postflight do
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/.config/devdeck/bin"]
    system_command "/bin/cp", args: ["#{staged_path}/bin/frontmost", "#{Dir.home}/.config/devdeck/bin/frontmost"]
    system_command "/bin/chmod", args: ["+x", "#{Dir.home}/.config/devdeck/bin/frontmost"]
    system_command "/bin/cp", args: ["#{staged_path}/bin/menuctl", "#{Dir.home}/.config/devdeck/bin/menuctl"]
    system_command "/bin/chmod", args: ["+x", "#{Dir.home}/.config/devdeck/bin/menuctl"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["-f", "#{Dir.home}/.config/devdeck/bin/frontmost"]
    system_command "/bin/rm", args: ["-f", "#{Dir.home}/.config/devdeck/bin/menuctl"]
  end

  # No zap stanza required

  caveats <<~EOS
    To start devdeck-server manually, run:
      devdeck-server

    To run as a background service, create a launchd plist or use:
      nohup devdeck-server &

    Context-aware deck switching requires the frontmost detector binary,
    which has been installed to ~/.config/devdeck/bin/frontmost

    AI-accurate shortcut generation requires the menuctl binary,
    which has been installed to ~/.config/devdeck/bin/menuctl
  EOS
end
