# This file was generated by GoReleaser. DO NOT EDIT.
cask "devdeck-server" do
  name "devdeck-server"
  desc "DevDeck server for the DevDeck mobile app"
  homepage "https://github.com/devdeck-app/devdeck-server"
  version "0.3.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devdeck-server"

  on_macos do
    on_intel do
      url "https://github.com/devdeck-app/devdeck-releases/releases/download/v#{version}/devdeck-server_#{version}_darwin_amd64.tar.gz"
      sha256 "12b1daeb347c781be9644a41fff2aec469117e39d6964d8a22e2b9023bc58ae7"
    end
    on_arm do
      url "https://github.com/devdeck-app/devdeck-releases/releases/download/v#{version}/devdeck-server_#{version}_darwin_arm64.tar.gz"
      sha256 "84b57b1abd201b4d82756b6be43b52b783f48767529cb1435a37b73962d2994e"
    end
  end

  postflight do
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/.config/devdeck/bin"]
    system_command "/bin/cp", args: ["#{staged_path}/bin/frontmost", "#{Dir.home}/.config/devdeck/bin/frontmost"]
    system_command "/bin/chmod", args: ["+x", "#{Dir.home}/.config/devdeck/bin/frontmost"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["-f", "#{Dir.home}/.config/devdeck/bin/frontmost"]
  end

  caveats do
    "To start devdeck-server manually, run:"
    "  devdeck-server"
    ""
    "To run as a background service, create a launchd plist or use:"
    "  nohup devdeck-server &"
    ""
    "Context-aware deck switching requires the frontmost detector binary,"
    "which has been installed to ~/.config/devdeck/bin/frontmost"
  end

  # No zap stanza required
end
