# This file was generated by GoReleaser. DO NOT EDIT.
cask "devdeck-server" do
  name "devdeck-server"
  desc "DevDeck server for the DevDeck mobile app"
  homepage "https://github.com/devdeck-app/devdeck-server"
  version "0.2.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devdeck-server"

  on_macos do
    on_intel do
      url "https://github.com/devdeck-app/devdeck-releases/releases/download/v#{version}/devdeck-server_#{version}_darwin_amd64.tar.gz"
      sha256 "b0479fb6373c324e66a462863c4e5091c8d499a32f0b36cc0aa3267f64f595ee"
    end
    on_arm do
      url "https://github.com/devdeck-app/devdeck-releases/releases/download/v#{version}/devdeck-server_#{version}_darwin_arm64.tar.gz"
      sha256 "cd0c9449e44ecf10b9e63804fbd9905281c52612dcf257883b318072547eb129"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devdeck-server"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/.config/devdeck/bin"]
    system_command "/bin/cp", args: ["#{staged_path}/bin/frontmost", "#{Dir.home}/.config/devdeck/bin/frontmost"]
    system_command "/bin/chmod", args: ["+x", "#{Dir.home}/.config/devdeck/bin/frontmost"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["-f", "#{Dir.home}/.config/devdeck/bin/frontmost"]
  end

  caveats do
    "To start devdeck-server manually, run:"
    "  devdeck-server"
    ""
    "To run as a background service, create a launchd plist or use:"
    "  nohup devdeck-server &"
    ""
    "Context-aware deck switching requires the frontmost detector binary,"
    "which has been installed to ~/.config/devdeck/bin/frontmost"
  end

  # No zap stanza required
end
