# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevdeckServer < Formula
  desc "DevDeck server for the DevDeck mobile app"
  homepage "https://github.com/devdeck-app/devdeck-server"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/devdeck-app/devdeck-server/releases/download/v0.1.0/devdeck-server_0.1.0_darwin_amd64.tar.gz"
    sha256 "a866bc9ed9f0baac1280c1135fb853d8f7899590b33907cbd646fc0b5d9b3d94"

    def install
      bin.install "devdeck-server"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/devdeck-app/devdeck-server/releases/download/v0.1.0/devdeck-server_0.1.0_darwin_arm64.tar.gz"
    sha256 "d097e0bad62894f9791e14378e13e6223fffc5e2e934e550fe20872f74e00f47"

    def install
      bin.install "devdeck-server"
    end
  end

  service do
    run [opt_bin]/"devdeck-server"
    keep_alive true
  end

  test do
    require "timeout"
    pid = fork do
      exec "#{bin}/devdeck-server"
    end
    sleep 2
    assert_predicate Process.kill(0, pid), :==, 1
    Process.kill("TERM", pid)
    Process.wait(pid)
  end
end
