# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevdeckServer < Formula
  desc "DevDeck server for the DevDeck mobile app"
  homepage "https://github.com/devdeck-app/devdeck-server"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/devdeck-app/devdeck-server/releases/download/v0.1.0/devdeck-server_0.1.0_darwin_amd64.tar.gz"
    sha256 "52bd9cec37dfe132326eaecf553577008415fb9f3f534533f247ee9591e639a2"

    def install
      bin.install "devdeck-server"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/devdeck-app/devdeck-server/releases/download/v0.1.0/devdeck-server_0.1.0_darwin_arm64.tar.gz"
    sha256 "180e6df7e69991b674cf94b825753b0e154eee77549a46694f26e7e33decc4f3"

    def install
      bin.install "devdeck-server"
    end
  end

  service do
    run [opt_bin/"devdeck-server"]
    keep_alive true
    working_dir var
    log_path var/"log/devdeck-server.log"
    error_log_path var/"log/devdeck-server.err.log"
  end

  test do
    require "timeout"
    pid = fork do
      exec "#{bin}/devdeck-server"
    end
    sleep 2
    assert_predicate Process.kill(0, pid), :==, 1
    Process.kill("TERM", pid)
    Process.wait(pid)
  end
end
