# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevdeckServer < Formula
  desc "DevDeck server for the DevDeck mobile app"
  homepage "https://github.com/devdeck-app/devdeck-server"
  version "0.1.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/devdeck-app/devdeck-server/releases/download/v0.1.3/devdeck-server_0.1.3_darwin_amd64.tar.gz"
    sha256 "0efa5ec65f67af6784007d77b77bbb3c580045b5b0d7d3764b2a1ac2a807c13f"

    def install
      bin.install "devdeck-server"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/devdeck-app/devdeck-server/releases/download/v0.1.3/devdeck-server_0.1.3_darwin_arm64.tar.gz"
    sha256 "63f5198da30059afff00cf389db3525ac13e0be62bf28c4969bc9d2e2edc2e8a"

    def install
      bin.install "devdeck-server"
    end
  end

  service do
    run [opt_bin/"devdeck-server"]
    keep_alive true
    working_dir var
    log_path var/"log/devdeck-server.log"
    error_log_path var/"log/devdeck-server.err.log"
  end

  test do
    require "timeout"
    pid = fork do
      exec "#{bin}/devdeck-server"
    end
    sleep 2
    assert_predicate Process.kill(0, pid), :==, 1
    Process.kill("TERM", pid)
    Process.wait(pid)
  end
end
